### ISSUE TITLE
AtomicBox should have bounds on its Send/Sync traits

### ISSUE THREAD

**Issue by ammaraskar** [vertexclique/lever#15]
Currently `AtomicBox` implements the Sync/Send traits unconditionally:

https://github.com/vertexclique/lever/blob/15a96c7f99e91f3d50c97ebba1147b3905f9f3dc/src/sync/atomics.rs#L104-L105

I think this should only be when `T: Sized + Sync` and `T: Sized + Send` respectively. Otherwise, this makes it possible to send across types that aren't safe to use across threads such as `Cell`s. Here's a demonstration that causes a data-race:

```rust
#![forbid(unsafe_code)]

use lever::sync::atomics::AtomicBox;

use std::cell::Cell;
use crossbeam_utils::thread;

#[derive(Debug, Clone, Copy)]
enum RefOrInt<'a> {
    Ref(&'a u64),
    Int(u64),
}
static SOME_INT: u64 = 123;

fn main() {
    let cell = Cell::new(RefOrInt::Ref(&SOME_INT));
    let atomic_box = AtomicBox::new(&cell);

    thread::scope(|s| {
        s.spawn(move |_| {
            let smuggled_cell = atomic_box.get();

            loop {
                // Repeatedly write Ref(&addr) and Int(0xdeadbeef) into the cell.
                smuggled_cell.set(RefOrInt::Ref(&SOME_INT));
                smuggled_cell.set(RefOrInt::Int(0xdeadbeef));
            }
        });

        loop {
            if let RefOrInt::Ref(addr) = cell.get() {
                // Hope that between the time we pattern match the object as a
                // `Ref`, it gets written to by the other thread.
                if addr as *const u64 == &SOME_INT as *const u64 {
                    continue;
                }

                // Due to the data race, obtaining Ref(0xdeadbeef) is possible
                println!("Pointer is now: {:p}", addr);
                println!("Dereferencing addr will now segfault: {}", *addr);
            }
        }
    });
}
```

This outputs:
```
Pointer is now: 0xdeadbeef

Return Code: -11 (SIGSEGV)
```

(Issue found by @sslab-gatech's Rust group)

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Once a fix is released to crates.io, please open a pull request to update the advisory with the patched version, or file an issue on [the advisory database repository](https://github.com/RustSec/advisory-db).

**Comment by o0Ignition0o** [comment]
Hey! thanks for opening the issue.

You're correct! I think @vertexclique has a patch and we can roll it out hopefully soon

**Comment by o0Ignition0o** [comment]
Added a regression test thanks to [trybuild](https://docs.rs/trybuild/1.0.39/trybuild/), super nice crate, i didn't know about it!

**Comment by o0Ignition0o** [comment]
@vertexclique can we close this now ? :) I'm going to submit a aptch to the rustsec advisory database

**Comment by vertexclique** [comment]
Truly, let's close it.
